config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" },
  :controllers => { registrations: 'users/registrations' }

  authenticated do
    root :to => 'dashboards#index', as: :authenticated
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'


  # get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'show_stock', to: 'stocks#show'
  get 'create_stock', to: 'stocks#create'
  get "/stocks", to: 'stocks#index', as: 'stocks'
  get 'buy_stock', to: 'stocks#buy_stock'
  get 'sell_stock', to: 'stocks#sell_stock'
  get 'transactions', to: 'transactions#index'

  patch 'users/:id/change_status' => 'users#change_status', as: :change_status_user

  post 'dashboards/add_balance'
  get '/pending' => 'users#pending', as: :pending_users
  get '/rejected' => 'users#rejected', as: :rejected_users
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user

    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
            endpoint: 'https://sandbox.iexapis.com/v1')
        begin
            new(ticker: ticker_symbol.upcase, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

	def index
	client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
		endpoint: 'https://sandbox.iexapis.com/v1')

	@trending_stocks = client.stock_market_list(:mostactive)
	end

	def search
		if params[:stock].present?
			@stock = Stock.new_lookup(params[:stock])
			if @stock
				respond_to do |format|
					format.js { render partial: 'users/result'}
				end
			else
				respond_to do |format|
					flash.now[:alert] = "Please enter a valid symbol to search"
					format.js { render partial: 'users/result' }
				end
			end
		else
			respond_to do |format|
				flash.now[:alert] = "Please enter a symbol to search"
				format.js { render partial: 'users/result' }
			end
		end
	end

	def show
		if params[:transaction] == 'buy'
			@transaction_path = buy_stock_path
			@page_header = 'Buy Stock'
			@button_class = 'btn-success add-user'
			@button_text = 'Buy'
		else
			@transaction_path = sell_stock_path
			@page_header = 'Sell Stock'
			@button_class = 'btn-danger delete-user'
			@button_text = 'Sell'
		end
		if params[:stock_ticker]
			@stock = Stock.new_lookup(params[:stock_ticker])
			@company_logo = "https://storage.googleapis.com/iex/api/logos/#{@stock.ticker.upcase}.png"
		else
			client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
				endpoint: 'https://sandbox.iexapis.com/v1')
			
			@stock = Stock.new
			@stock.ticker = params[:symbol]
			@company_logo = "https://storage.googleapis.com/iex/api/logos/#{@stock.ticker}.png"
			@stock.name = params[:company_name]
			
			@stock.last_price = params[:latest_price]
		end
	end

	# def create
	# 	stock = Stock.new(name: params[:name], ticker: params[:ticker], last_price: params[:last_price], quantity: params[:quantity])
	# 	stock.save
	# 	redirect_to root_path
	# end

	#! refactor
	def buy_stock
		user = User.find(current_user.id)
		existing_stock = Stock.find_by(:user_id => current_user.id, :ticker => params[:ticker])
		total_amount = params[:quantity].to_i * params[:last_price].to_i
		stock = Stock.new(name: params[:name], ticker: params[:ticker], quantity: params[:quantity], user_id: current_user.id)
		if total_amount <= current_user.balance && params[:quantity].to_i > 0
			if user.update(balance: user.balance - total_amount)
				if existing_stock
					existing_stock.update(quantity: existing_stock.quantity.to_i + params[:quantity].to_i)
				else
					stock.save
				end
				Transaction.create(name: params[:name], ticker: params[:ticker], quantity: params[:quantity], user_id: current_user.id, transaction_type: 'buy', price: params[:last_price])
				# redirect_to root_path
				respond_to do |format|
					format.html { redirect_to root_path, notice: "You have successfully bought #{params[:quantity]} share(s) of #{params[:name]} (#{params[:ticker]})" }
					# format.json { head :no_content }
				end
			end
		else
			respond_to do |format|
				format.html { redirect_to root_path, alert: "Invalid quantity" }
				# format.json { head :no_content }
			end
		end	
	end

	def sell_stock
		user = User.find(current_user.id)
		existing_stock = Stock.find_by(:user_id => current_user.id, :ticker => params[:ticker], quantity: 1..)
		total_amount = params[:quantity].to_i * params[:last_price].to_i
		
		if existing_stock && params[:quantity].to_i > 0 && params[:quantity].to_i <= existing_stock.quantity.to_i
			if user.update(balance: user.balance + total_amount)
				existing_stock.update(quantity: existing_stock.quantity.to_i - params[:quantity].to_i)
				Transaction.create(name: params[:name], ticker: params[:ticker], quantity: params[:quantity], user_id: current_user.id, transaction_type: 'sell', price: params[:last_price])
				redirect_to root_path
			end	
		else
			respond_to do |format|
				format.html { redirect_to root_path, notice: "Invalid quantity" }
				# format.json { head :no_content }
			end
		end	
	end
end

app/views/stocks/_trending.html.erb
<h1>Trending Stocks</h1>

<% @trending_stocks.each do |stock| %>
<%#= link_to user_path(user) do %>
	<div class= "user-list-card">
		<div>
			<span class="user-list-card-name"><%= stock.symbol %></span>
			<p><%= stock.company_name %></p>
			<p><%= stock.latest_price %></p>
		</div>

		<div class="user-button-container">
			<%= link_to root_path, class: "btn btn-success edit-user" do %> 
					<i class='bx bxs-edit' ></i> 
			<% end %>
			<%= link_to root_path, class: "btn btn-danger delete-user" do %> 
					<i class='bx bxs-trash-alt' ></i> 
			<% end %>
		</div>
	</div>
<%# end %>
<% end %>



<%= @trending_stocks.inspect %>

app/views/stocks/index.html.erb
<div class="row">
<div class="col">
<h3>Search Stocks</h3>

        <%= form_tag search_stock_path, remote: true, method: :get do %>
            <div class="form-group row">
                <div class="col-sm-9">
                    <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
                </div>
                <div class="col-sm-3 no-left-padding">
                    <%= button_tag type: :submit, class: "btn btn-success add-user" do %>
                        <i class="bx bx-search"></i>
                    <% end %>
                </div>
            </div>
        <% end %>

    <div id="results">
        
    </div></div>
<div class="col">
<h3>Trending Stocks</h3>

<div class= "user-list">
    <% if @trending_stocks.any? %>
        <% @trending_stocks.each do |stock|%>
            <div class= "user-list-card">
                <div>
                    <span class="user-list-card-name"><%= stock.company_name %> (<%= stock.symbol %>)</span>
                <p><%= stock.change_percent_s %> | <%= number_to_currency(stock.latest_price)%>  per share </p>
                </div>
                <div class="user-button-container">
                    <%= link_to show_stock_path(:stock_ticker => stock.symbol, :transaction => 'buy'), class: "btn btn-success add-user" do %> 
                            Buy
                    <% end %>
                    <%= link_to show_stock_path(:stock_ticker => stock.symbol, :transaction => 'sell'), class: "btn btn-danger delete-user" do %> 
                            Sell
                    <% end %>
                </div>
            </div>
        <% end %>
    <% else %>
        <div class= "user-list-card-blank">
            <i class='bx bx-confused' ></i> 
            <p>There seems to be a problem loading the information</p>
        </div>
    <% end %>
</div>  
</div>
</div>

app/views/stocks/show.html.erb
<h1><%= @page_header %></h1>

  <div class="jumbotron user-info company-info">
    <img src="<%= @company_logo %>" class="company-logo" alt="">
    <div>
    <h1 class="display-4"><%= @stock.name %></h1>
    <strong>Symbol: </strong> <%= @stock.ticker.upcase %> |
    <strong>Price: </strong> <%= @stock.last_price %>
    </div>
  </div>

<%= form_tag @transaction_path, method: :get do %>
	<div class="form-group row">
        <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :name, @stock.name, class: "form-control form-control-lg", type: :hidden %>
        </div>

        <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :ticker, @stock.ticker, class: "form-control form-control-lg", type: :hidden %>
        </div>

        <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :last_price, @stock.last_price, class: "form-control form-control-lg", type: :hidden %>
        </div>

        <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :quantity, params[:quantity], placeholder: "Quantity", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        
        <div class="col-sm-3">
                <%= button_tag type: :submit, class: "btn #{@button_class}" do %>
                        <%= @button_text %>
                <% end %>
        </div>
    </div>
<% end %>

app/views/stocks/show_buy.html.erb
<h1>Buy Stock </h1>

  <div class="jumbotron user-info company-info">
    <img src="<%= @company_logo %>" class="company-logo" alt="">
    <div>
    <h1 class="display-4"><%= @stock.name %></h1>
    <strong>Symbol: </strong> <%= @stock.ticker.upcase %> |
    <strong>Price: </strong> <%= @stock.last_price %>
    </div>
  </div>

<%= form_tag buy_stock_path, method: :get do %>
    <div class="form-group row">

        <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :name, @stock.name, class: "form-control form-control-lg", type: :hidden %>
        </div>

        <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :ticker, @stock.ticker, class: "form-control form-control-lg", type: :hidden %>
        </div>

        <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :last_price, @stock.last_price, class: "form-control form-control-lg", type: :hidden %>
        </div>

        <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :quantity, params[:quantity], placeholder: "Quantity", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        
        <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success add-user" do %>
                        Buy
                <% end %>
        </div>
    </div>
<% end %>