config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" },
  :controllers => { registrations: 'users/registrations' }

  authenticated do
    root :to => 'dashboards#index', as: :authenticated
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'


  # get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'show_stock', to: 'stocks#show'
  get 'create_stock', to: 'stocks#create'
  get "/stocks", to: 'stocks#index', as: 'stocks'
  get 'buy_stock', to: 'stocks#buy_stock'
  get 'sell_stock', to: 'stocks#sell_stock'
  get 'transactions', to: 'transactions#index'

  patch 'users/:id/change_status' => 'users#change_status', as: :change_status_user

  post 'dashboards/add_balance'
  get '/pending' => 'users#pending', as: :pending_users
  get '/rejected' => 'users#rejected', as: :rejected_users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :stocks
  has_many :transactions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        #  validates :name, presence: true
        #  validates :email, presence: true, uniqueness: true
        #  validates :password, confirmation: true, length: { minimum: 6 }
        #  validates :password_confirmation, presence: true
         
  validates_presence_of :name
  # after_create :account_created_mail
  # def account_created_mail
  #   UserMailer.account_created(self).deliver_later
  # end   

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :require_no_authentication, only: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  # POST /resource
  def create
    super
    if resource.valid? 
      UserMailer.account_created(resource).deliver_later
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  protected

  def sign_up(resource_name, resource)
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :restrict_action


  def index
    @users = User.all.order('status')
  end

  def pending
    @users = User.all.where(:admin => false, :status => 'pending')
  end

  def rejected
    @users = User.all.where(:admin => false, :status => 'rejected')
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|  
      if @user.save
        UserMailer.account_admin_created(@user).deliver_later
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        # render :new
        format.html { render :partial => 'users/new', status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end

  end



  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end


  def my_portfolio
  end

  #! change function
  def change_status
    @user = User.find(params[:id])
    @user.update(status: params[:status])
    if params[:status] == 'approved'
      UserMailer.account_approved(@user).deliver_later
    end
    redirect_to params[:path]
  end
  
  
  private

  def restrict_action
    redirect_to root_path unless current_user.admin? 
  end

  def user_params
      params.require(:user).permit(:email, :name, :password, :status, :balance)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new.html.erb
<div class="modal-header">
<h4 class="modal-title" id="myModalLabel">Add User</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
  
</div>
<div class="modal-body">
    <div class="form-container form-group">
        <%= render partial: "devise/shared/signup_form", :locals => { :resource => @user } %>
        <% if false %> 
            <%= form_for @user, url: create_user_path do |f| %>
            <%= render "users/shared/error_messages", resource: @user %>

            <p>
                <%= f.label :name%><br/>
                <%= f.text_field :name, class: "form-control" %>
            </p>

            <p>
                <%= f.label :email %><br/>
                <%= f.text_field :email, class: "form-control" %>
            </p>

            <p>
                <%= f.label :password %><br/>
                <%= f.password_field :password, class: "form-control" %>
            </p>

            <p>
                <%= f.label :password_confirmation %><br />
                <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
            </p>
            <p>
                <%= f.submit "Create User", class: "btn btn-block btn-primary" %>
            </p>
            <% end %>
        <% end %>
    </div>
</div>

app/views/users/_result.html.erb
<div class="results-block">
	<%= render 'layouts/messages' %>
</div>

<% if @stock %>
	<div class="user-list">
		<div class="user-list-card">
			<div>
				<span class="user-list-card-name"><%= @stock.name %> (<%= @stock.ticker %>)</span>
				<p><%= number_to_currency(@stock.last_price)%>  per share </p>
			</div>
			<%= link_to show_stock_path(:stock_ticker => @stock.ticker.upcase, :transaction => 'buy') do %>
				<button type="button" class="btn btn-success add-user">Buy</button>
			<% end %>
		</div>
		
	</div>
<% end%>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/edit.html.erb
<h3>Edit User</h3>

<%= form_with model: @user do |f| %>
<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: "form-control" %>
</p>

<p>
    <%= f.label :email %><br/>
    <%= f.text_field :email, class: "form-control"%>
</p>
<br><br>
<p>
    <%= f.submit "Edit User",  class: "btn btn-success add-user"%>
</p>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<div class="table-responsive-md">
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Balance</th>
                <th>Registration Status</th>
                <th></th>
            <tr>
        </thead>

        <tbody>
            <% @users.where(:admin => false, :status => 'approved').each do |user| %>
                    <tr>
                        <td><%= user.name %></td>
                        <td><%= user.email %></td>
                        <td><%= user.balance %></td>
                        <td class='user-status'><%= user.status %></td>
                        <td><%= link_to 'Show', user_path(user) %>
                        <%= link_to 'Edit', edit_user_path(user) %>
                        <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"}  %></td>
                    <tr>
            <% end %>
        <tbody>
    </table>
</div>

<h1>Pending Users</h1>

<div class="table-responsive-md">
<% if @users.where(:admin => false, :status => 'pending').any? %>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Registration Status</th>
                <th></th>
            <tr>
        </thead>

        <tbody>
            <% @users.where(:admin => false, :status => 'pending' || nil).each do |user| %>
                    <tr>
                        <td><%= user.name %></td>
                        <td><%= user.email %></td>
                        <td class='user-status'><%= user.status %></td>
                        <td><%# <%= link_to destroy_user_session_path, method: :delete , class: "btn btn-xs btn-success" do %>
                            <%= link_to change_status_user_path(user, {status: 'approved'}), method: :patch, class: "btn btn-xs btn-success" do%>
                                    <i class='bx bx-check nav_icon'></i> 
                            <% end %>
                            <%= link_to change_status_user_path(user, {status: 'rejected'}), method: :patch, class: "btn btn-outline-danger" do %>
                                <i class='bx bx-x nav_icon'></i> 
                            <% end %>
                        </td>
                    <tr>
            <% end %>
            
        <tbody>
    </table>
    <% else %>
        <tr>
        <p>There are no records to display.</p>
        </tr>
    <% end %>
</div>

<h1>Rejected Users</h1>
<div class="table-responsive-md">
    <% if @users.where(:admin => false, :status => 'rejected').any? %>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Registration Status</th>
                    <th></th>
                <tr>
            </thead>

            <tbody>
            
                <% @users.where(:admin => false, :status => 'rejected').each do |user| %>
                        <tr>
                            <td><%= user.name %></td>
                            <td><%= user.email %></td>
                            <td class='user-status'><%= user.status %></td>
                            <td><%# <%= link_to destroy_user_session_path, method: :delete , class: "btn btn-xs btn-success" do %>
                                <%= link_to change_status_user_path(user, {status: 'approved'}), method: :patch, class: "btn btn-xs btn-success" do%>
                                        <i class='bx bx-check nav_icon'></i> 
                                <% end %>
                            </td>
                        <tr>
                <% end %>
            
            <tbody>
        </table>
    <% else %>
        <tr>
        <p>There are no records to display.</p>
        </tr>
    <% end %>
</div>
<%= link_to "Add User", new_user_registration_path %>

<%if false%>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='search-area'>
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :stock, 'params[:stock]', placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div id="results">
    
</div>

app/views/users/new.html.erb
<h1>Add User</h1>

<% if @user.errors.any? %>
<h2>The following errors prevented the article from getting created</h2>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_with model: @user do |f| %>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
</p>

<p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
</p>

<p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
</p>
<p>
    <%= f.submit "Create User" %>
</p>

<% end %>

app/views/users/new.js.erb
$('#modal-window').find('.modal-content').html("<%= j (render 'users/new') %>");
$('#modal-window').modal();

app/views/users/pending.html.erb
<h3>Pending Users</h3>
<% if @users.any? %>
    <div class="user-list">
        <% @users.each do |user| %>
            <%= link_to user_path(user) do %>
                <div class= "user-list-card">
                    <div class= "user-list-card-text">
                    <span class="user-list-card-name"><%= user.name %></span><i class="bx <%= status_mark(user) %>"></i>
                    <p><%= user.email %></p>
                    </div>
                    <div class="user-button-container">
                        <%= link_to change_status_user_path(user, {status: 'approved', path: pending_users_path}), method: :patch, class: "btn btn-success approve-user" do %> 
                                <i class='bx bx-check' ></i> 
                        <% end %>
                        <%= link_to change_status_user_path(user, {status: 'rejected', path: pending_users_path}), method: :patch, class: "btn btn-success reject-user" do %> 
                                <i class='bx bx-x' ></i> 
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
<% else %>
    <div class= "user-list-card-blank">
        <i class='bx bx-happy-beaming' ></i> 
        <p>You're all caught up. No pending users.</p>
    </div>
<% end %>

app/views/users/rejected.html.erb
<h3>Rejected Users</h3>
<% if @users.any? %>
    <div class="user-list"> 
        <% @users.each do |user| %>
            <%= link_to user_path(user) do %>
                <div class= "user-list-card">
                    <div class= "user-list-card-text">
                    <span class="user-list-card-name"><%= user.name %></span><i class="bx <%= status_mark(user) %>"></i>
                    <p><%= user.email %></p>
                    </div>
                    <div class="user-button-container">
                        <%= link_to change_status_user_path(user, {status: 'approved', path: rejected_users_path}), method: :patch, class: "btn btn-success approve-user" do %> 
                                <i class='bx bx-check' ></i> 
                        <% end %>
                        <%= link_to user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger delete-user" do %> 
                                <i class='bx bxs-trash-alt' ></i> 
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
<% else %>
    <div class= "user-list-card-blank">
        <i class='bx bx-happy-beaming' ></i> 
        <p>You're all caught up. No rejected users.</p>
    </div>
<% end %>

app/views/users/show.html.erb
<div class="jumbotron user-info">
  <div class="user-info-name" >
    <i class="bx <%= status_mark(@user) %>"></i>
    <h1 class="display-4">
      <%= @user.name %>
    </h1>
    
  </div>
  <p class="lead">
    Email: <%= @user.email %>
  </p>
  <p class="lead">
    Balance: <%= number_to_currency(@user.balance) %>
  </p>
  <br/>
  <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-secondary" %> 
  <%= link_to 'Back', users_path, class: "btn btn-dark"  %>

</div>