config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" },
  :controllers => { registrations: 'users/registrations' }

  authenticated do
    root :to => 'dashboards#index', as: :authenticated
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'


  # get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'show_stock', to: 'stocks#show'
  get 'create_stock', to: 'stocks#create'
  get "/stocks", to: 'stocks#index', as: 'stocks'
  get 'buy_stock', to: 'stocks#buy_stock'
  get 'sell_stock', to: 'stocks#sell_stock'
  get 'transactions', to: 'transactions#index'

  patch 'users/:id/change_status' => 'users#change_status', as: :change_status_user

  post 'dashboards/add_balance'
  get '/pending' => 'users#pending', as: :pending_users
  get '/rejected' => 'users#rejected', as: :rejected_users
end

app/views/shared/_navbar.html.erb
<%# <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand">Stock app</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    
</nav> %>

<div class="l-navbar" id="nav-bar">
        <nav class="nav">
        
            <div> <div class="header_toggle nav_logo"> <i class='bx bx-menu' id="header-toggle-side"></i> </div>
            <% if current_user.admin? %>            
                <div class="nav_list"> 
                    <%= link_to root_path, class: "nav_link #{active_class(users_path)}" do %> <i class='bx bx-group nav_icon'></i> <span class="nav_name">All Users</span> <% end %>
                    <%= link_to pending_users_path, class: "nav_link #{active_class(pending_users_path)}" do %> <i class='bx bx-user-check nav_icon'></i> <span class="nav_name">Pending Users</span> <% end %>
                    <%= link_to rejected_users_path, class: "nav_link #{active_class(rejected_users_path)}" do %> <i class='bx bx-user-minus nav_icon'></i> <span class="nav_name">Rejected Users</span><% end %>
                    <%= link_to new_user_registration_path, class: "nav_link #{active_class(new_user_registration_path)}" do %> <i class='bx bx-user-plus nav_icon'></i> <span class="nav_name">Add User</span> <% end %>
                </div>
            <% else %>
                <div class="nav_list"> 
                    <%= link_to root_path, class: "nav_link #{active_class(root_path)}" do %> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Dashboard</span> <% end %>
                    <% if current_user.status == 'approved' %>  
                        <%= link_to stocks_path, class: "nav_link #{active_class(stocks_path)}" do %> <i class='bx bx-candles nav_icon'></i> <span class="nav_name">Stock Market</span> <% end %>
                        <%= link_to transactions_path, class: "nav_link #{active_class(transactions_path)}" do %> <i class='bx bx-history nav_icon'></i> <span class="nav_name">Transactions</span> <% end %>
                    <% end %>
                </div>
            <% end %>
            </div> 
            <%= link_to destroy_user_session_path, method: :delete , class: "nav_link" do %><i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Log Out</span><% end %>
        </nav>
    </div>

app/views/shared/_topbar.html.erb
<%#= link_to root_path, class: "nav_logo" do%> <%#i class='bx bx-line-chart nav_logo-icon'></i> <span class="nav_logo-name">Stock App</span> <% end %>
        <% if current_user %>
            <header class="header" id="header">
                <div>
                <p class="header_text"><%= current_user.email %></p>
                </div>
                <div class="header_nav">
                <div class="header_toggle header_toggle-header"> <i class='bx bx-menu' id="header-toggle-header"></i> </div>
                <%= link_to root_path do%> <%= image_tag('Logo-long-col.svg', class: "header-logo") %> <% end %>
                <%#= link_to root_path, class: "header_logo" do%> <%#div><i class='bx bx-line-chart header_logo-icon'></i> <span class="header_logo-name">Stock App</span> </div><%# end %>
                <%# %= link_to "Logout", destroy_user_session_path, method: :delete %>
                </div>
            </header>
        <% else %>
            <header class="header-home" id="header">
                <div>
                    <%= link_to "Login", new_user_session_path, class: "btn btn-light" %>
                    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-light" %>
                </div>
                <div>
                    <%= link_to root_path do%><%= image_tag('Logo-long.svg', class: "header-logo") %> <% end %>
                </div>
            </header>
        <% end %>